sudo: false
language: node_js
matrix:
  include:
    - node_js: '6'
after_success:
  - cat ./coverage/coverage.json | ./node_modules/.bin/adana -F . > ./coverage/istanbul.json
  - bash <(curl -s https://codecov.io/bash) -f ./coverage/istanbul.json
