sudo: false
language: node_js
matrix:
  include:
    # Run tests in Node.js 6.x
    - node_js: '6'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8

before_install:
  # Use GCC 4.8 if it's available
