// flow-typed signature: 52ccdf49283c60a4552ab3bff8fcd227
// flow-typed version: <<STUB>>/cuid_v1.3.8/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cuid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cuid' {
  declare module.exports: () => string;
}
